#!/usr/bin/env bash

# Exit on error.
set -e

# Load environment variables.
source .env

echo "Creating user accounts..."

export PGPASSWORD=$POSTGRES_PASSWORD
POSTGRES="psql -U $POSTGRES_USER"

$POSTGRES <<-EOSQL
    CREATE USER "$POSTGRES_FRONTDOOR_USER" WITH CREATEDB PASSWORD '$POSTGRES_FRONTDOOR_PASSWORD';
    CREATE USER "$POSTGRES_KITCHEN_USER" WITH CREATEDB PASSWORD '$POSTGRES_KITCHEN_PASSWORD';
    CREATE USER "$POSTGRES_ORDER_USER" WITH CREATEDB PASSWORD '$POSTGRES_ORDER_PASSWORD';
    CREATE USER "$POSTGRES_RESTAURANT_USER" WITH CREATEDB PASSWORD '$POSTGRES_RESTAURANT_PASSWORD';
EOSQL

echo "Created user accounts."